### ISSUE TITLE
Circular data causes an error in failed tests.

### ISSUE THREAD

**Issue by Dave-Baum** [hbenl/vscode-jasmine-test-adapter#35]
If a test fails and the actual value is some sort of circular data structure, then an error is thrown when trying to JSON encode the failure event.  As a result the test status does not update in the test explorer.  For example, this test:

it('test', () => {
  const x: any[] = [];
  x.push(x);
  expect(x).toEqual([]);
});

Leads to this output:

Suite error: undefined
  Message:
[31m    TypeError: Converting circular structure to JSON[0m
  Stack:
        at <Jasmine>
        at process.target._send (internal/child_process.js:675:23)
        at process.target.send (internal/child_process.js:586:19)
        at RunTestsReporter.process.send [as sendMessage] (/Users/dave/.vscode/extensions/hbenl.vscode-jasmine-test-adapter-1.6.0/out/worker/runTests.js:6:57)
        at RunTestsReporter.specDone (/Users/dave/.vscode/extensions/hbenl.vscode-jasmine-test-adapter-1.6.0/out/worker/runTestsReporter.js:36:18)
        at <Jasmine>

**Comment by hbenl** [comment]
Thanks, this is fixed in version 1.6.1.

**Comment by Dave-Baum** [comment]
Thank you for the quick fix - it works perfectly.
